### PR TITLE
fixing error with delete http request removing questions key in data.json object

### LINKED ISSUE #2: Fix HTTP request functions returning undefined

### PR DESCRIPTION
**Pull request by halimahexe**
The delete request was overwriting the data.json and removing the `{ "questions": }` container for the array, so I've fixed that.

Relates #39

### CODE REVIEW

**Review by Gaajia — APPROVED** [review]
the delete functions. works good job.

**Review by oskarprzybylski23 — CHANGES_REQUESTED** [review]
please remove console.logs

**Review by oskarprzybylski23 — APPROVED** [review]
Good to merge

**Comment by halimahexe** [comment]
Resolves #2

**Pull request merged**
